blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Get Help
    url: https://github.com/stuartasiimwe7/blackboxml/discussions
    about: Start a discussion if you have general questions, need help, or want to brainstorm ideas.

  - name: 🛡 Report a Security Vulnerability
    url: https://github.com/stuartasiimwe7/blackboxml/security/policy
    about: Please report security vulnerabilities through the security policy page.

  - name: 📄 Read the Contribution Guidelines
    url: https://github.com/stuartasiimwe7/blackboxml/blob/main/.github/CONTRIBUTING.md
    about: Please read our contributing guidelines before submitting a new issue or pull request.

  - name: 📜 Review the Code of Conduct
    url: https://github.com/stuartasiimwe7/blackboxml/blob/main/.github/CODE_OF_CONDUCT.md
    about: Please make sure to adhere to our Code of Conduct while participating.