blank_issues_enabled: false
contact_links:
  - name: Ask a Question or Get Help
    url: https://github.com/stuartasiimwe7/traceml/discussions
    about: Start a discussion if you have general questions, need help, or want to brainstorm ideas.

  - name: Report a Security Vulnerability
    url: https://github.com/stuartasiimwe7/traceml/security/policy
    about: Please report security vulnerabilities through the security policy page.

  - name: Read the Contribution Guidelines
    url: https://github.com/stuartasiimwe7/traceml/blob/main/.github/CONTRIBUTING.MD
    about: Please read our contributing guidelines before submitting a new issue or pull request.

  - name: Review the Code of Conduct
    url: https://github.com/stuartasiimwe7/traceml/blob/main/.github/CODE_OF_CONDUCT.MD
    about: Please make sure to adhere to our Code of Conduct while participating.